app/items/views.py
# IMPORTS
from flask import render_template, Blueprint, request, redirect, url_for, flash
from flask_login import current_user, login_required
from app import db
from app.models import Items, User
from .forms import ItemsForm, EditItemsForm


# CONFIG
items_blueprint = Blueprint('items', __name__, template_folder='templates')


# ROUTES
@items_blueprint.route('/all_items', methods=['GET', 'POST'])
@login_required
def all_items():
    """Render homepage"""
    all_user_items = Items.query.filter_by(user_id=current_user.id)
    return render_template('all_items.html', items=all_user_items)


@items_blueprint.route('/add_item', methods=['GET', 'POST'])
@login_required
def add_item():
    form = ItemsForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_item = Items(form.name.data, form.notes.data,
                                 current_user.id)
                db.session.add(new_item)
                db.session.commit()
                message = "<strong>Well done!</strong> Item added successfully!"
                flash(message, 'success')
                return redirect(url_for('home'))
            except:
                db.session.rollback()
                message = "<strong>Oh snap!</strong>! Unable to add item."
                flash(message, 'danger')
    return render_template('add_item.html', form=form)


@items_blueprint.route('/edit_item/<items_id>', methods=['GET', 'POST'])
@login_required
def edit_item(items_id):
    form = EditItemsForm(request.form)
    item_with_user = db.session.query(Items, User).join(User).filter(Items.id == items_id).first()
    if item_with_user is not None:
        if current_user.is_authenticated and item_with_user.Items.user_id == current_user.id:
            if request.method == 'POST':
                if form.validate_on_submit():
                    try:
                        item = Items.query.get(items_id)
                        item.name = form.name.data
                        item.notes = form.notes.data
                        db.session.commit()
                        message = "Item edited successfully!"
                        flash(message, 'success')
                        return redirect(url_for('home'))
                    except:
                        db.session.rollback()
                        message = "<strong>Error!</strong> Unable to edit item."
                        flash(message, 'danger')
            return render_template('edit_item.html', item=item_with_user, form=form)
        else:
            message = "<strong>Error!</strong> Incorrect permissions to access this item."
            flash(message, 'danger')
    else:
        message = "<strong>Error!</strong> Item does not exist."
        flash(message, 'danger')
    return redirect(url_for('home'))


@items_blueprint.route('/delete_item/<items_id>')
@login_required
def delete_item(items_id):
    item = Items.query.filter_by(id=items_id).first_or_404()

    if not item.user_id == current_user.id:
        message = "<strong>Error!</strong> Incorrect permissions to delete this item."
        flash(message, 'danger')
        return redirect(url_for('home'))

    db.session.delete(item)
    db.session.commit()
    flash('{} was deleted.'.format(item.name), 'success')
    return redirect(url_for('items.all_items'))

app/users/views.py
# IMPORTS
from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from itsdangerous import URLSafeTimedSerializer
from threading import Thread
from flask_mail import Message
from datetime import datetime, timedelta

from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from app import app, db, mail
from app.models import User


# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# HELPERS
def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)


# ROUTES
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                send_confirmation_email(new_user.email)
                message = "<strong>Success!</strong> Thanks for registering. Please check your email to confirm your email address."
                flash(message, 'success')
                return redirect(url_for('home'))
            except IntegrityError:
                db.session.rollback()
                message = "<strong>Error!</strong> Unable to process registration."
                flash(message, 'danger')
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                if user.is_email_confirmed is not True:
                    user.authenticated = True
                    db.session.add(user)
                    db.session.commit()
                    login_user(user)
                    return redirect(url_for('users.resend_email_confirmation'), )
                if user.is_email_confirmed is True:
                    user.authenticated = True
                    user.last_logged_in = user.current_logged_in
                    user.current_logged_in = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    login_user(user)
                    message = "<strong>Welcome back!</strong> You are now successfully logged in."
                    flash(message, 'success')
                    return redirect(url_for('home'))
            else:
                message = "<strong>Error!</strong> Incorrect login credentials."
                flash(message, 'danger')
    return render_template('login.html', form=form)


@users_blueprint.route('/user_profile', methods=['GET', 'POST'])
@login_required
def user_profile():
    return render_template('user_profile.html')


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        message = "The confirmation link is invalid or has expired."
        flash(message, 'danger')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        message = "Account already confirmed. Please login."
        flash(message, 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        message = "Thank you for confirming your email address!"
        flash(message, 'success')

    return redirect(url_for('home'))


@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            message = "Invalid email address!"
            flash(message, 'danger')
            return render_template('password_reset_email.html', form=form)
        if user.email_confirmed:
            send_password_reset_email(user.email)
            message = "Please check your email for a password reset link."
            flash(message, 'success')
        else:
            message = "Your email address must be confirmed before attempting a password reset."
            flash(message, 'danger')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        message = "The password reset link is invalid or has expired."
        flash(message, 'danger')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            message = "Invalid email address!"
            flash(message, 'danger')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        message = "Your password has been updated!"
        flash(message, 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('admin_view_users.html', users=users)


@users_blueprint.route('/admin_dashboard')
@login_required
def admin_dashboard():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        kpi_mau = User.query.filter(User.last_logged_in > (datetime.today() - timedelta(days=30))).count()
        kpi_total_confirmed = User.query.filter_by(email_confirmed=True).count()
        kpi_mau_percentage = (100 / kpi_total_confirmed) * kpi_mau
        return render_template('admin_dashboard.html', users=users, kpi_mau=kpi_mau, kpi_total_confirmed=kpi_total_confirmed, kpi_mau_percentage=kpi_mau_percentage)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    message = "<strong>Goodbye!</strong> You are now logged out."
    flash(message, 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            message = "Password has been updated!"
            flash(message, 'success')
            return redirect(url_for('users.user_profile'))

    return render_template('password_change.html', form=form)


@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        message = "Email sent to confirm your email address. Please check your inbox!"
        flash(message, 'success')
        user = current_user
        user.authenticated = False
        db.session.add(user)
        db.session.commit()
        logout_user()
    except IntegrityError:
        message = "Error!  Unable to send email to confirm your email address."
        flash(message, 'danger')
        user = current_user
        user.authenticated = False
        db.session.add(user)
        db.session.commit()
        logout_user()
    return redirect(url_for('users.login'))


@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user

app/templates/410.html
{% extends "_base.html" %}
{% block title %}410{% endblock %}

{% block content %}

<h2>Gone</h2>

{% endblock %}

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{{ url_for('static', filename='images/favicon.png') }}" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
          Flask App Blueprint</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    {% include "includes/flash_messages.html" %}

    <div class="container my-5">
      <h1>{{ self.title() }}</h1>
      <hr>
      <div>
        {% block content %}{% endblock %}
      </div>
    </div>

    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-body-secondary">&copy; 2024 Company, Inc</p>
    
        <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
          <img src="{{ url_for('static', filename='images/favicon.png') }}" alt="Logo" width="24" height="24">
        </a>
    
        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
        </ul>
      </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/_formshelper.html
{% macro render_field(field) %}
{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}

app/templates/add_item.html
{% extends "_base.html" %}
{% block title %}Add Item{% endblock %}
{% from "_formshelper.html" import render_field %}
{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('items.add_item') }}" method="post" name="itemsform">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.name.label }}
          {{ render_field(form.name, class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.notes.label }}
          {{ render_field(form.notes, class="form-control") }}
        </div>
        <input type="submit" value="Add Item" class="btn btn-lg btn-success">
    </form>
  </div>
  <div class="col-md-6">
    <h4>On adding items</h4>
    <p>If you need hep, provide it here.</p>
  </div>
</div>

{% endblock %}

app/templates/admin_dashboard.html
{% extends "_base.html" %}
{% from "_formshelper.html" import render_field %}
{% block title %}Admin: Dashboard{% endblock %}

{% block content %}

<div class="row mx-auto">
  <div class="card m-3" style="max-width: 20rem;">
    <h5 class="card-header">Monthly Active Users</h5>
    <div class="card-body">
      <h1 class="display-1 text-center">{{ kpi_mau }}</h5>
      <p class="card-text">Total number of users logged in in the last 30 days.</p>
      <a href="{{ url_for('users.admin_view_users') }}" class="btn btn-primary">View all users</a>
    </div>
  </div>

  <div class="card m-3" style="max-width: 20rem;">
    <h5 class="card-header">Total Sign Ups</h5>
    <div class="card-body">
      <h1 class="display-1 text-center">{{ kpi_total_confirmed }}</h5>
      <p class="card-text">Total users with a confirmed email address.</p>
      <a href="{{ url_for('users.admin_view_users') }}" class="btn btn-primary">View all users</a>
    </div>
  </div>

  <div class="card m-3" style="max-width: 20rem;">
    <h5 class="card-header">MAU as % of Sign Ups</h5>
    <div class="card-body">
      <h1 class="display-1 text-center">{{ kpi_mau_percentage }}%</h5>
      <p class="card-text">Percentage of monthly active users on total sign ups.</p>
      <a href="{{ url_for('users.admin_view_users') }}" class="btn btn-primary">View all users</a>
    </div>
  </div>
</div>

{% endblock %}

app/templates/admin_view_users.html
{% extends "_base.html" %}
{% from "_formshelper.html" import render_field %}
{% block title %}Admin: All Users{% endblock %}

{% block content %}



<table class="table table-stripe">
  <thead>
    <tr>
      <th class="border-top-0">User ID</th>
      <th class="border-top-0">Email</th>
      <th class="border-top-0">Role</th>
      <th class="border-top-0">Registration Date</th>
      <th class="border-top-0">Email Confirmed?</th>
      <th class="border-top-0">Email Confirmed On</th>
      <th class="border-top-0">Last Login</th>
      </tr>
  </thead>
  <tbody>
    {% for user in users %}
      <tr>
        <td> {{ user.id }} </td>
        <td> {{ user.email }} </td>
        <td> {{ user.role }} </td>
        <td> {{ user.registered_on }} </td>
        <td> {{ user.email_confirmed }} </td>
        <td> {{ user.email_confirmed_on }} </td>
        <td> {{ user.last_logged_in }} </td>
      </tr>
    {% endfor %}
  </tbody>
</table>



{% endblock %}

app/templates/all_items.html
{% extends "_base.html" %}
{% block title %}All Items{% endblock %}
{% block content %}

{% if items[0] == NULL %}
<div class="panel-body">
  <p>No items are added yet, <a href="{{ url_for('items.add_item') }}">add a new item</a>.</p>
</div>
{% else %}
<table class="table table-stripe">
  <thead>
    <tr>
      <th class="border-top-0">Name</th>
      <th class="border-top-0">Notes</th>
      <th class="border-top-0"></th>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr>
      <td>{{ item.name }}</td>
      <td>
        {{ item.notes }}
      </td>
      <td>
        <a href="{{ url_for('items.edit_item', items_id=item.id) }}">Edit</a>
        <a href="{{ url_for('items.delete_item', items_id=item.id) }}">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% endblock %}

app/templates/delete_item.html
{% extends "_base.html" %}
{% block title %}Delete Item{% endblock %}
{% block content %}

<form action="{{ url_for('items.delete_item', items_id=items[0].id) }}" method="post" name="deleteitemsform">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="border-top-0">Name</th>
            <th class="border-top-0">Notes</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
          <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.notes }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    <input type="submit" value="Delete Item" class="btn btn-lg btn-success">
</form>

{% endblock %}

app/templates/email_change.html
{% extends "_base.html" %}
{% block title %}Change Email Address{% endblock %}
{% from "_formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('users.user_email_change') }}" method="post">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.email.label }}
        {{ render_field(form.email, placeholder="Enter New Email Address", class="form-control") }}
      </div>
      <input type="submit" value="Change Email Address" class="btn btn-lg btn-success">
    </form>
  </div>
</div>

{% endblock %}

app/templates/email_confirmation.html
{# project/templates/email_confirmation.html #}

<p>Your account on Flask App Blueprint was successfully created.</p>

<p>Please click the link below to confirm your email address and activate your account:</p>

<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>

app/templates/email_password_reset.html
{# project/templates/email_password_reset.html #}

<p>You requested that the password for your Flask App Blueprint account be reset.</p>

<p>Please click the link below to reset your password:</p>

<p><a href="{{ password_reset_url }}">{{ password_reset_url }}</a></p>

app/templates/home.html
{% extends "_base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}

<div class="card">
  <div class="card-body">
    <h4 class="card-title">My Items</h4>
    {% if items[0] == NULL %}
    <p class="card-text">No items are added yet, <a href="{{ url_for('items.add_item') }}">add a new item</a>.</p>
    {% else %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td>{{ item.name }}</td>
          <td>{{ item.notes }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock %}

app/templates/password_change.html
{% extends "_base.html" %}
{% block title %}Change Password{% endblock %}
{% from "_formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('users.user_password_change') }}" method="post">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.password.label }}
        {{ render_field(form.password, placeholder="Enter New Password", class="form-control") }}
      </div>
      <input type="submit" value="Change Password" class="btn btn-lg btn-success">
    </form>
  </div>
</div>

{% endblock %}

app/templates/password_reset_email.html
{% extends "_base.html" %}
{% block title %}Forgot password{% endblock %}
{% from "_formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('users.reset') }}" method="POST">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.email.label }}
        {{ render_field(form.email, class="form-control", placeholder="Enter your email address") }}
      </div>
      <input type="submit" value="Forgot password" class="btn btn-lg btn-success">
    </form>
  </div>
</div>

{% endblock %}